# Generated by Django 4.1.7 on 2023-03-15 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(max_length=70, verbose_name='Имя команды')),
                ('description', models.TextField(verbose_name='Описание команды')),
                ('add_employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники команды')),
            ],
            options={
                'verbose_name': 'Команда ',
                'verbose_name_plural': 'Команды',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('last_week', models.TextField(blank=True, verbose_name='What did you do last week?')),
                ('this_week', models.TextField(blank=True, verbose_name='What are you working on until the next week?')),
                ('next_week', models.TextField(blank=True, verbose_name='What are your plans for the next week?')),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False, verbose_name='Отчет отправлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-id'],
            },
        ),
    ]
