# Generated by Django 4.1.7 on 2023-03-17 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_teamemployee_options_alter_report_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamemployee',
            options={'ordering': ['-id'], 'verbose_name': 'Команда ', 'verbose_name_plural': 'Команды'},
        ),
        migrations.RemoveField(
            model_name='teamemployee',
            name='add_employee',
        ),
        migrations.AddField(
            model_name='teamemployee',
            name='employee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Отчет отправлен'),
        ),
        migrations.AlterField(
            model_name='teamemployee',
            name='description',
            field=models.TextField(verbose_name='Описание команды'),
        ),
        migrations.AlterField(
            model_name='teamemployee',
            name='name_team',
            field=models.CharField(max_length=70, verbose_name='Имя команды'),
        ),
    ]
