# Generated by Django 4.1.7 on 2023-03-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_report_sent_remove_teamemployee_add_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportStatus',
        ),
    ]
